version: "3.7"
services:
  planer-app:
    build: .
    container_name: planer
    image: planer:latest
    environment:
      - MYSQL_HOST=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/planer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=lozinka
    ports:
      - 80:8080
    networks:
      - planer-network
    volumes:
      - java-data:/app/uploads
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    image: mysql
    networks:
      - planer-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=planer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  planer-network:
    driver: bridge

volumes:
  mysql-data:
  java-data:
